### ISSUE TITLE
target 'make Debian' is not correctly installed

### ISSUE THREAD

**Issue by jean-marc-LACROIX** [sbxg/manifests#1]
Jean, 
I am running commit 790cf0be330772b385daec1a7e692bd69020ed48 on 'manifests.git' in order to create new 4.7.3 kernel for Cubietruck.
My commands are ...

step 1: 
make MANIFESTS_REVISION="dev/jeanmarc/kernel-4.7" menuconfig

step 2:
step 4: initialize and fetch all repo on github
make MANIFESTS_REVISION="dev/jeanmarc/kernel-4.7" init sync 

step 3: 
make Debian

The kernel is correctly generated with correct naming convention
linux-image-4.7.3-c25a26d-d7f6728-00330-gd7f6728_4.7.3+c25a26d~d7f6728_armhf.deb

When running previous SBXG kernel (4.6.2), and installing 4.63 via apt command, following behaviour is :

dpkg -i /tmp/linux-image-4.7.3-c25a26d-d7f6728-00330-gd7f6728_4.7.3+c25a26d~d7f6728_armhf.deb

 dpkg -i /tmp/linux-image-4.7.3-c25a26d-d7f6728-00330-gd7f6728_4.7.3+c25a26d~d7f6728_armhf.deb

Linux cubietruck 4.7.2-00186-g84fae3f #8 SMP PREEMPT Thu Sep 8 10:19:17 CEST 2016 armv7l GNU/Linux
_4.7.3+c25a26d~d7f6728_armhf.deb inux-image-4.7.3-c25a26d-d7f6728-00330-gd7f6728
Selecting previously unselected package linux-image-4.7.3-c25a26d-d7f6728-00330-gd7f6728.
(Reading database ... 19343 files and directories currently installed.)
Preparing to unpack .../linux-image-4.7.3-c25a26d-d7f6728-00330-gd7f6728_4.7.3+c25a26d~d7f6728_armhf.deb ...
Done.
Unpacking linux-image-4.7.3-c25a26d-d7f6728-00330-gd7f6728 (4.7.3+c25a26d~d7f6728) ...
Setting up linux-image-4.7.3-c25a26d-d7f6728-00330-gd7f6728 (4.7.3+c25a26d~d7f6728) ...

 Hmm. There is a symbolic link /lib/modules/4.7.3-c25a26d-d7f6728-00330-gd7f6728/build
 However, I can not read it: No such file or directory
 Therefore, I am deleting /lib/modules/4.7.3-c25a26d-d7f6728-00330-gd7f6728/build

 Hmm. The package shipped with a symbolic link /lib/modules/4.7.3-c25a26d-d7f6728-00330-gd7f6728/source
 However, I can not read the target: No such file or directory
 Therefore, I am deleting /lib/modules/4.7.3-c25a26d-d7f6728-00330-gd7f6728/source

Running depmod.
Examining /etc/kernel/postinst.d.
run-parts: executing /etc/kernel/postinst.d/apt-auto-removal 4.7.3-c25a26d-d7f6728-00330-gd7f6728 /boot/uImage-4.7.3-c25a26d-d7f6728-00330-gd7f6728
_4.7.3+c25a26d~d7f6728_armhf.deb ^Cux-image-4.7.3-c25a26d-d7f6728-00330-gd7f6728_

root@cubietruck:~# dpkg -l |grep linux-image
ii  linux-image-4.7.3-c25a26d-d7f6728-00330-gd7f6728 4.7.3+c25a26d~d7f6728    armhf        Linux kernel binary image for version 4.7.3-c25a26d-d7f6728-00330-gd7f6728
root@cubietruck:~#

After rebooting, kernel 4.6.3 is not booting, but previous kernel is booting (4.7.2 in my conf)

Starting kernel ...

[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 4.7.2-00186-g84fae3f (local@solo) (gcc version 4.7.2 (Debian 4.7.2-5) ) #8 SMP PREEMPT Thu Sep 8 10:19:17 CEST 2016
[    0.000000] CPU: ARMv7 Processor [410fc074] revision 4 (ARMv7), cr=10c5387d
[ ........

In fact , it seems the 4.7.3 installation is not done correctly, because after booting ...

root@cubietruck:~# ls -altr /boot
total 14568
drwxr-xr-x  2 root root    4096 Jan  1  1970 .
drwxr-xr-x 21 root root    4096 Aug 29  2016 ..
-rw-r--r--  1 root root   30881 Sep  7  2016 sun7i-a20-cubieboard2.dtb
-rw-r--r--  1 root root 6388168 Sep  8  2016 uImage
-rw-r--r--  1 root root   32542 Sep  8  2016 sun7i-a20-cubietruck.dtb
-rw-r--r--  1 root root  148660 Sep  8  2016 config
-rw-r--r--  1 root root     353 Sep  8  2016 boot.scr
-rw-r--r--  1 root root  148781 Sep 12  2016 config-4.7.3-c25a26d-d7f6728-00330-gd7f6728
-rw-------  1 root root 6265864 Sep 12  2016 uImage-4.7.3-c25a26d-d7f6728-00330-gd7f6728
-rw-------  1 root root 1839486 Sep 12  2016 System.map-4.7.3-c25a26d-d7f6728-00330-gd7f6728

In order to resolv it, i make : 
 rm /boot/uImage && ln -s /boot/uImage-4.7.3-c25a26d-d7f6728-00330-gd7f6728 /boot/uImage
and after rebooting, Cubietruck boot 4.7.3 as follow
Starting kernel ...

[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 4.7.3-c25a26d-d7f6728-00330-gd7f6728 (local@solo) (gcc version 4.7.2 (Debian 4.7.2-5) ) #1 SMP PREEMPT Mon Sep 12 13:02:46 CEST 2016
[    0.000000] CPU: ARMv7 Processor [410fc074] revision 4 (ARMv7), cr=10c5387d
[    0.000000] CPU: div instructions available: patching division code
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] Machine model: Cubietech Cubietruck
[    0.000000] Truncating RAM at 0x40000000-0xbfd00000 to -0x70000000
[    0.000000] Consider using a HIGHMEM enabled kernel.
[    0.000000] cma: Reserved 16 MiB at 0x6f000000
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] psci: probing for conduit method from DT.
[    0.000000] psci: Using PSCI v0.1 Function IDs from DT
[    0.000000] percpu: Embedded 14 pages/cpu @ee8f9000 s24896 r8192 d24256 u57344
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 194880
[    0.000000] Kernel command line: console=ttyS0,115200 earlyprintk hdmi.audio=EDID:0 disp.screen0_output_mode=EDID:1280x1024p60 root=/dev/mmcblk0p1 rootwait panic=10

Conclusions:
 P1: Perhaps a problem when postinst in the package because ....
root@cubietruck:~# ls -altr /etc/kernel/postinst.d/zz-uimage-select
ls: cannot access /etc/kernel/postinst.d/zz-uimage-select: No such file or directory

P2: 
There are still warning when installing via dpkg (please look at trace above )

P3: I suggest to create a symlink with SBXG project  on /boot/uImage file so that when future installation is done via dpkg, only the link must be done

Thanks in advance for your help

**Comment by jeanguyomarch** [comment]
I think this has been resolved in SBXG core.
